name: {{name.snakeCase()}}_{{suffix.snakeCase()}}
description: Package accessing the {{name.snakeCase()}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  rxdart: ^0.27.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.5
  very_good_analysis: ^3.0.1