name: {{name.snakeCase()}}_{{suffix.snakeCase()}}
description: Package accessing the {{name.snakeCase()}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  rxdart: ^0.27.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: ^3.1.0